baseURL = 'https://example.org/'
languageCode = 'de-de'
title = 'beyond code podcast'

[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 1

[[menu.main]]
identifier = 'contact'
name = 'Kontakt'
url = '/contact/'
weight = 2

[[menu.main]]
identifier = 'episodes'
name = 'Episoden'
url = '/episodes/'
weight = 3

[build]
writeStats = true


[esbuild]
target = 'es6'
