baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'beyond code podcast'
theme = 'beyondcode-theme'

[[menu.main]]
identifier = 'episodes'
name = 'Episoden'
url = '/episodes'
pre = '<span class="bg-red-200 text-red-700 px-4 py-2 rounded-full hover:bg-white hover:text-red-500 hover:border hover:border-red-500 hover:shadow-md transition-all duration-300"></span>'
weight = 1

[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about'
weight = 2

[[menu.main]]
identifier = 'contact'
name = 'Kontakt'
url = '/contact'
weight = 3
